server:
  port: 8080
  servlet:
    context-path: /toupiao

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb?serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: 327429

    #jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8


mybatis:
  type-aliases-package: com.hb.pojo
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  page-size-zero: true
  pageSizeZero: true
